// Meserii raw data: [name, COR, medianSalary, demand, [competences]]
// 20 meserii per domain × 20 domains = 400 meserii

export const meseriiByDomain = {
  'it-comunicatii': [
    ['Dezvoltator Software','251201',8500,'ridicat',['programare','analiza-datelor','rezolvarea-problemelor','lucru-echipa']],
    ['Analist Programator','251202',7500,'ridicat',['programare','analiza-datelor','comunicare']],
    ['Dezvoltator Web','251203',7000,'ridicat',['programare','design-grafic','rezolvarea-problemelor']],
    ['Inginer DevOps','252301',9500,'ridicat',['programare','administrare-sisteme','rezolvarea-problemelor']],
    ['Manager Proiect IT','133101',10000,'ridicat',['managementul-proiectelor','comunicare','leadership']],
    ['Administrator Rețele','252201',6500,'mediu',['administrare-sisteme','rezolvarea-problemelor','securitate-cibernetica']],
    ['Tester Software','251204',6000,'ridicat',['programare','atentie-detalii','rezolvarea-problemelor']],
    ['Architect Software','251205',12000,'mediu',['programare','analiza-datelor','leadership']],
    ['Inginer Date','252101',9000,'ridicat',['programare','analiza-datelor','rezolvarea-problemelor']],
    ['Analist Business IT','251206',7000,'mediu',['analiza-datelor','comunicare','planificare-organizare']],
    ['Administrator Baze de Date','252102',7500,'mediu',['administrare-sisteme','analiza-datelor','atentie-detalii']],
    ['Specialist Securitate Cibernetică','252901',9000,'ridicat',['securitate-cibernetica','administrare-sisteme','rezolvarea-problemelor']],
    ['Dezvoltator Mobile','251207',8000,'ridicat',['programare','design-grafic','rezolvarea-problemelor']],
    ['Designer UX/UI','216601',7000,'ridicat',['design-grafic','comunicare','rezolvarea-problemelor']],
    ['Inginer Machine Learning','252103',11000,'ridicat',['programare','analiza-datelor','rezolvarea-problemelor']],
    ['Specialist Cloud','252302',9500,'ridicat',['administrare-sisteme','securitate-cibernetica','programare']],
    ['Consultant IT','252202',8000,'mediu',['comunicare','rezolvarea-problemelor','managementul-proiectelor']],
    ['Administrator Sisteme','252203',6500,'mediu',['administrare-sisteme','securitate-cibernetica','rezolvarea-problemelor']],
    ['Inginer QA','251208',6500,'mediu',['programare','atentie-detalii','rezolvarea-problemelor']],
    ['Scrum Master','133102',8500,'mediu',['managementul-proiectelor','comunicare','leadership']],
  ],

  'constructii': [
    ['Electrician Constructor','741101',4500,'ridicat',['electricitate','citirea-planurilor','protectia-muncii','lucru-echipa']],
    ['Inginer Constructor','214201',7500,'ridicat',['citirea-planurilor','managementul-proiectelor','rezolvarea-problemelor']],
    ['Instalator Sanitar','712601',4200,'ridicat',['citirea-planurilor','rezolvarea-problemelor','protectia-muncii']],
    ['Fierar Betonist','711401',3800,'mediu',['citirea-planurilor','protectia-muncii','lucru-echipa']],
    ['Zugrav-Vopsitor','713101',3500,'mediu',['atentie-detalii','protectia-muncii','lucru-echipa']],
    ['Tâmplar','752201',3800,'mediu',['citirea-planurilor','atentie-detalii','protectia-muncii']],
    ['Zidar','711101',3600,'mediu',['citirea-planurilor','protectia-muncii','lucru-echipa']],
    ['Dulgher','711201',3800,'mediu',['citirea-planurilor','protectia-muncii','rezolvarea-problemelor']],
    ['Faianțar-Mozaicar','712201',4000,'mediu',['atentie-detalii','citirea-planurilor','protectia-muncii']],
    ['Montator Structuri Metalice','721201',4200,'mediu',['citirea-planurilor','sudura','protectia-muncii']],
    ['Topograf','216501',5500,'mediu',['citirea-planurilor','analiza-datelor','atentie-detalii']],
    ['Operator Macara','834101',4500,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Izolator Industrial','712301',3800,'mediu',['citirea-planurilor','protectia-muncii','atentie-detalii']],
    ['Instalator Gaze','712602',4500,'ridicat',['citirea-planurilor','protectia-muncii','rezolvarea-problemelor']],
    ['Operator Buldozer','834201',4000,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Laborant Construcții','311901',3500,'scazut',['analiza-datelor','atentie-detalii','protectia-muncii']],
    ['Inspector Calitate Construcții','214202',6000,'mediu',['managementul-calitatii','citirea-planurilor','atentie-detalii']],
    ['Diriginte Șantier','214203',7000,'mediu',['managementul-proiectelor','citirea-planurilor','leadership']],
    ['Geotehnician','214204',5500,'scazut',['analiza-datelor','citirea-planurilor','rezolvarea-problemelor']],
    ['Proiectant Construcții','214205',7000,'mediu',['citirea-planurilor','rezolvarea-problemelor','atentie-detalii']],
  ],

  'sanatate': [
    ['Medic Generalist','221101',8000,'ridicat',['ingrijirea-pacientilor','comunicare','rezolvarea-problemelor']],
    ['Asistent Medical','222101',4500,'ridicat',['ingrijirea-pacientilor','comunicare','prim-ajutor']],
    ['Medic Stomatolog','226101',9000,'ridicat',['ingrijirea-pacientilor','atentie-detalii','comunicare']],
    ['Farmacist','226201',6500,'mediu',['ingrijirea-pacientilor','atentie-detalii','comunicare']],
    ['Fizioterapeut','226301',4500,'ridicat',['ingrijirea-pacientilor','comunicare','rezolvarea-problemelor']],
    ['Nutriționist','226501',4000,'mediu',['ingrijirea-pacientilor','comunicare','analiza-datelor']],
    ['Laborant Medical','321101',3800,'mediu',['atentie-detalii','analiza-datelor','protectia-muncii']],
    ['Asistent Farmacie','321201',3500,'mediu',['ingrijirea-pacientilor','atentie-detalii','comunicare']],
    ['Brancardier','532901',2800,'scazut',['prim-ajutor','lucru-echipa','protectia-muncii']],
    ['Infirmier','532101',2800,'mediu',['ingrijirea-pacientilor','prim-ajutor','lucru-echipa']],
    ['Tehnician Radiologie','321202',4200,'mediu',['atentie-detalii','protectia-muncii','ingrijirea-pacientilor']],
    ['Optometrist','226401',4500,'mediu',['ingrijirea-pacientilor','atentie-detalii','comunicare']],
    ['Psiholog Clinician','226302',5000,'mediu',['comunicare','rezolvarea-problemelor','ingrijirea-pacientilor']],
    ['Logoped','226303',4200,'mediu',['comunicare','ingrijirea-pacientilor','rezolvarea-problemelor']],
    ['Kinetoterapeut','226304',4500,'ridicat',['ingrijirea-pacientilor','rezolvarea-problemelor','comunicare']],
    ['Moașă','222201',4500,'mediu',['ingrijirea-pacientilor','prim-ajutor','comunicare']],
    ['Tehnician Dentar','321301',4000,'mediu',['atentie-detalii','ingrijirea-pacientilor','rezolvarea-problemelor']],
    ['Maseur Medical','325501',3500,'mediu',['ingrijirea-pacientilor','comunicare','atentie-detalii']],
    ['Paramedic','224101',4000,'ridicat',['prim-ajutor','ingrijirea-pacientilor','rezolvarea-problemelor']],
    ['Asistent Igienă Publică','222102',3800,'scazut',['ingrijirea-pacientilor','comunicare','protectia-muncii']],
  ],

  'educatie': [
    ['Profesor Informatică','233001',5000,'mediu',['predare-educatie','programare','comunicare']],
    ['Profesor Matematică','233002',4500,'mediu',['predare-educatie','rezolvarea-problemelor','comunicare']],
    ['Profesor Limba Română','233003',4200,'mediu',['predare-educatie','comunicare','atentie-detalii']],
    ['Profesor Limba Engleză','233004',4500,'mediu',['predare-educatie','limbi-straine','comunicare']],
    ['Profesor Fizică','233005',4200,'mediu',['predare-educatie','rezolvarea-problemelor','analiza-datelor']],
    ['Profesor Chimie','233006',4200,'scazut',['predare-educatie','rezolvarea-problemelor','protectia-muncii']],
    ['Profesor Biologie','233007',4200,'scazut',['predare-educatie','comunicare','rezolvarea-problemelor']],
    ['Profesor Istorie','233008',4000,'scazut',['predare-educatie','comunicare','analiza-datelor']],
    ['Profesor Geografie','233009',4000,'scazut',['predare-educatie','comunicare','analiza-datelor']],
    ['Profesor Educație Fizică','233010',3800,'mediu',['predare-educatie','fitness-antrenament','comunicare']],
    ['Educator Grădiniță','234101',3500,'mediu',['predare-educatie','comunicare','lucru-echipa']],
    ['Învățător','234201',3800,'mediu',['predare-educatie','comunicare','planificare-organizare']],
    ['Bibliotecar','262201',3000,'scazut',['comunicare','planificare-organizare','atentie-detalii']],
    ['Consilier Școlar','235101',4000,'mediu',['comunicare','rezolvarea-problemelor','predare-educatie']],
    ['Formator Profesional','235201',4500,'mediu',['predare-educatie','comunicare','planificare-organizare']],
    ['Instructor Auto','516501',3800,'mediu',['conducere-vehicule','comunicare','predare-educatie']],
    ['Profesor Muzică','233011',3800,'scazut',['predare-educatie','comunicare','atentie-detalii']],
    ['Profesor Arte Vizuale','233012',3800,'scazut',['predare-educatie','design-grafic','comunicare']],
    ['Pedagog Școlar','235102',3200,'scazut',['predare-educatie','comunicare','lucru-echipa']],
    ['Logoped Școlar','235103',4200,'mediu',['comunicare','ingrijirea-pacientilor','predare-educatie']],
  ],

  'industrie-productie': [
    ['Operator CNC','722301',4500,'ridicat',['operare-utilaje','citirea-planurilor','atentie-detalii']],
    ['Lăcătuș Mecanic','722201',4000,'ridicat',['operare-utilaje','citirea-planurilor','rezolvarea-problemelor']],
    ['Sudor','721101',4500,'ridicat',['sudura','protectia-muncii','atentie-detalii']],
    ['Strungar','722101',4200,'mediu',['operare-utilaje','citirea-planurilor','atentie-detalii']],
    ['Frezor','722302',4000,'mediu',['operare-utilaje','citirea-planurilor','atentie-detalii']],
    ['Electronist','742101',4500,'mediu',['electricitate','rezolvarea-problemelor','atentie-detalii']],
    ['Electromecanic','741201',4200,'mediu',['electricitate','operare-utilaje','rezolvarea-problemelor']],
    ['Mecatronist','742201',5000,'ridicat',['operare-utilaje','programare','rezolvarea-problemelor']],
    ['Operator Linie Producție','821101',3200,'mediu',['operare-utilaje','protectia-muncii','lucru-echipa']],
    ['Tehnician Întreținere','311301',4200,'ridicat',['operare-utilaje','electricitate','rezolvarea-problemelor']],
    ['Inginer Producție','214901',7000,'mediu',['managementul-proiectelor','managementul-calitatii','rezolvarea-problemelor']],
    ['Inspector Calitate Producție','214902',5000,'mediu',['managementul-calitatii','atentie-detalii','analiza-datelor']],
    ['Operator Roboți Industriali','742202',5500,'ridicat',['operare-utilaje','programare','rezolvarea-problemelor']],
    ['Tehnician Automatist','311302',5000,'ridicat',['operare-utilaje','programare','electricitate']],
    ['Maistru Producție','312101',4500,'mediu',['leadership','operare-utilaje','managementul-calitatii']],
    ['Ambalator','832001',2800,'scazut',['atentie-detalii','protectia-muncii','lucru-echipa']],
    ['Inginer Procese','214903',6500,'mediu',['managementul-proiectelor','analiza-datelor','rezolvarea-problemelor']],
    ['Tehnician Metrolog','311303',4000,'scazut',['atentie-detalii','analiza-datelor','managementul-calitatii']],
    ['Operator Presă','821201',3200,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Sculer Matrițer','722303',4500,'mediu',['operare-utilaje','citirea-planurilor','atentie-detalii']],
  ],

  'transport-logistica': [
    ['Șofer TIR','833201',5500,'ridicat',['conducere-vehicule','planificare-organizare','protectia-muncii']],
    ['Curier','933101',3500,'ridicat',['conducere-vehicule','comunicare','planificare-organizare']],
    ['Logistician','432101',5000,'mediu',['planificare-organizare','gestionare-stocuri','analiza-datelor']],
    ['Pilot Avion','315101',15000,'scazut',['conducere-vehicule','comunicare','rezolvarea-problemelor','limbi-straine']],
    ['Mecanic Auto Transport','723101',4000,'ridicat',['mecanica-auto','rezolvarea-problemelor','protectia-muncii']],
    ['Dispecer Transport','432201',3800,'mediu',['planificare-organizare','comunicare','rezolvarea-problemelor']],
    ['Operator Depozit','432301',3200,'mediu',['gestionare-stocuri','operare-utilaje','protectia-muncii']],
    ['Motostivuitorist','834301',3500,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Controlor Trafic Aerian','315201',12000,'scazut',['comunicare','rezolvarea-problemelor','limbi-straine','atentie-detalii']],
    ['Marinar','835101',5000,'scazut',['protectia-muncii','lucru-echipa','conducere-vehicule']],
    ['Mecanic Naval','723201',4500,'scazut',['rezolvarea-problemelor','operare-utilaje','protectia-muncii']],
    ['Conductor Tren','831101',5000,'mediu',['conducere-vehicule','atentie-detalii','protectia-muncii']],
    ['Mecanic Locomotivă','831201',5500,'mediu',['operare-utilaje','rezolvarea-problemelor','protectia-muncii']],
    ['Inspector ITP','311401',4500,'mediu',['mecanica-auto','atentie-detalii','legislatie-juridica']],
    ['Agent Vamal','335101',4000,'mediu',['legislatie-juridica','comunicare','atentie-detalii']],
    ['Planificator Rute','432202',4000,'mediu',['planificare-organizare','analiza-datelor','rezolvarea-problemelor']],
    ['Gestionar Stoc','432302',3500,'mediu',['gestionare-stocuri','atentie-detalii','planificare-organizare']],
    ['Șofer Autobuz','833101',3800,'mediu',['conducere-vehicule','comunicare','protectia-muncii']],
    ['Manipulant Marfă','933201',2800,'mediu',['protectia-muncii','lucru-echipa','gestionare-stocuri']],
    ['Expeditor','432203',3500,'mediu',['planificare-organizare','comunicare','gestionare-stocuri']],
  ],

  'agricultura': [
    ['Inginer Agronom','213101',5000,'mediu',['agricultura-zootehnie','analiza-datelor','managementul-proiectelor']],
    ['Fermier','611101',3500,'mediu',['agricultura-zootehnie','planificare-organizare','rezolvarea-problemelor']],
    ['Veterinar','225101',5500,'mediu',['ingrijirea-pacientilor','rezolvarea-problemelor','comunicare']],
    ['Tractorist','834401',3200,'mediu',['conducere-vehicule','operare-utilaje','protectia-muncii']],
    ['Apicultor','612101',3000,'scazut',['agricultura-zootehnie','atentie-detalii','protectia-muncii']],
    ['Viticultor','611201',3200,'scazut',['agricultura-zootehnie','atentie-detalii','planificare-organizare']],
    ['Silvicultor','621101',3500,'mediu',['agricultura-zootehnie','protectia-muncii','planificare-organizare']],
    ['Pădurar','621201',3000,'mediu',['agricultura-zootehnie','protectia-muncii','comunicare']],
    ['Zootehnist','213201',4000,'mediu',['agricultura-zootehnie','analiza-datelor','planificare-organizare']],
    ['Mecanic Agricol','723301',3500,'mediu',['mecanica-auto','operare-utilaje','rezolvarea-problemelor']],
    ['Operator Irigații','834501',3000,'scazut',['operare-utilaje','agricultura-zootehnie','protectia-muncii']],
    ['Grădinar','611301',2800,'scazut',['agricultura-zootehnie','atentie-detalii','protectia-muncii']],
    ['Peisagist','216201',4500,'mediu',['design-grafic','agricultura-zootehnie','comunicare']],
    ['Horticultor','611302',3200,'scazut',['agricultura-zootehnie','atentie-detalii','rezolvarea-problemelor']],
    ['Tehnician Alimentar','314101',4000,'mediu',['managementul-calitatii','atentie-detalii','protectia-muncii']],
    ['Inspector Fitosanitar','213301',3800,'scazut',['agricultura-zootehnie','legislatie-juridica','atentie-detalii']],
    ['Piscicultor','622101',3200,'scazut',['agricultura-zootehnie','protectia-muncii','rezolvarea-problemelor']],
    ['Inginer Silvic','213401',4500,'mediu',['agricultura-zootehnie','managementul-proiectelor','analiza-datelor']],
    ['Operator Recoltare','834502',3000,'mediu',['operare-utilaje','agricultura-zootehnie','protectia-muncii']],
    ['Laborant Agricol','314201',3500,'scazut',['analiza-datelor','atentie-detalii','agricultura-zootehnie']],
  ],

  'horeca': [
    ['Bucătar','512001',3800,'ridicat',['pregatire-culinara','lucru-echipa','protectia-muncii']],
    ['Ospătar','513101',3000,'ridicat',['relatii-clienti','comunicare','lucru-echipa']],
    ['Barman','513201',3200,'mediu',['pregatire-culinara','relatii-clienti','comunicare']],
    ['Recepționer Hotel','422101',3200,'mediu',['relatii-clienti','comunicare','limbi-straine']],
    ['Cofetar-Patiser','751201',3500,'mediu',['pregatire-culinara','atentie-detalii','protectia-muncii']],
    ['Pizzar','512002',3200,'mediu',['pregatire-culinara','lucru-echipa','protectia-muncii']],
    ['Brutar','751101',3200,'mediu',['pregatire-culinara','protectia-muncii','atentie-detalii']],
    ['Sommelier','513202',4000,'scazut',['pregatire-culinara','comunicare','relatii-clienti']],
    ['Șef Bucătar','343101',6000,'mediu',['pregatire-culinara','leadership','managementul-proiectelor']],
    ['Manager Restaurant','141201',5500,'mediu',['leadership','planificare-organizare','relatii-clienti']],
    ['Cameristă','911201',2800,'mediu',['atentie-detalii','protectia-muncii','lucru-echipa']],
    ['Concierge','422102',3000,'scazut',['relatii-clienti','comunicare','limbi-straine']],
    ['Organizator Evenimente','333901',4500,'mediu',['planificare-organizare','comunicare','relatii-clienti']],
    ['Barista','513203',2800,'mediu',['pregatire-culinara','relatii-clienti','comunicare']],
    ['Manager Hotel','141101',6500,'mediu',['leadership','planificare-organizare','limbi-straine']],
    ['Animator Turistic','516101',2800,'scazut',['comunicare','limbi-straine','lucru-echipa']],
    ['Ghid Turistic','511301',3200,'mediu',['comunicare','limbi-straine','relatii-clienti']],
    ['Agent Turism','422201',3200,'mediu',['relatii-clienti','comunicare','vanzare-negociere']],
    ['Carmangier','751301',3500,'mediu',['pregatire-culinara','protectia-muncii','atentie-detalii']],
    ['Ajutor Bucătar','941201',2500,'mediu',['pregatire-culinara','lucru-echipa','protectia-muncii']],
  ],

  'comert-vanzari': [
    ['Agent Vânzări','332201',4000,'ridicat',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Casier','523001',2800,'mediu',['atentie-detalii','relatii-clienti','comunicare']],
    ['Merchandiser','524101',3200,'mediu',['planificare-organizare','atentie-detalii','comunicare']],
    ['Manager Magazin','142001',5000,'mediu',['leadership','planificare-organizare','gestionare-stocuri']],
    ['Consultant Vânzări','332202',4500,'mediu',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Reprezentant Comercial','332203',4500,'mediu',['vanzare-negociere','comunicare','planificare-organizare']],
    ['Key Account Manager','332204',7000,'mediu',['vanzare-negociere','leadership','comunicare']],
    ['Specialist E-commerce','332205',5500,'ridicat',['marketing-digital','analiza-datelor','vanzare-negociere']],
    ['Buyer','332301',5000,'mediu',['vanzare-negociere','analiza-datelor','planificare-organizare']],
    ['Category Manager','332302',5500,'mediu',['analiza-datelor','planificare-organizare','vanzare-negociere']],
    ['Specialist Trade Marketing','243301',5000,'mediu',['marketing-digital','vanzare-negociere','analiza-datelor']],
    ['Visual Merchandiser','524102',3500,'scazut',['design-grafic','atentie-detalii','comunicare']],
    ['Promoter','524103',2800,'mediu',['comunicare','relatii-clienti','vanzare-negociere']],
    ['Specialist Achiziții','332303',4500,'mediu',['vanzare-negociere','analiza-datelor','planificare-organizare']],
    ['Telemarketer','524201',3000,'mediu',['comunicare','vanzare-negociere','relatii-clienti']],
    ['Vânzător','522001',2800,'ridicat',['relatii-clienti','comunicare','vanzare-negociere']],
    ['Director Vânzări','122101',9000,'mediu',['leadership','vanzare-negociere','managementul-proiectelor']],
    ['Broker Asigurări','332101',4500,'mediu',['vanzare-negociere','comunicare','legislatie-juridica']],
    ['Agent Comercial','332206',3800,'mediu',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Sales Engineer','243401',7000,'mediu',['vanzare-negociere','rezolvarea-problemelor','comunicare']],
  ],

  'finante-banci': [
    ['Contabil','331301',4500,'ridicat',['contabilitate-finante','atentie-detalii','legislatie-juridica']],
    ['Auditor','241101',6000,'mediu',['contabilitate-finante','analiza-datelor','atentie-detalii']],
    ['Analist Financiar','241201',7000,'mediu',['contabilitate-finante','analiza-datelor','rezolvarea-problemelor']],
    ['Economist','263101',5000,'mediu',['contabilitate-finante','analiza-datelor','comunicare']],
    ['Broker Bursier','331101',8000,'scazut',['contabilitate-finante','analiza-datelor','rezolvarea-problemelor']],
    ['Specialist Credite','331201',4000,'mediu',['contabilitate-finante','comunicare','legislatie-juridica']],
    ['Consultant Fiscal','241301',6000,'mediu',['contabilitate-finante','legislatie-juridica','comunicare']],
    ['Controller Financiar','241202',7500,'mediu',['contabilitate-finante','analiza-datelor','managementul-proiectelor']],
    ['Risk Manager','241203',8000,'mediu',['analiza-datelor','contabilitate-finante','rezolvarea-problemelor']],
    ['Actuar','212101',8000,'scazut',['analiza-datelor','rezolvarea-problemelor','contabilitate-finante']],
    ['Trezorier','331302',6000,'scazut',['contabilitate-finante','atentie-detalii','planificare-organizare']],
    ['Analist Investiții','241204',7500,'mediu',['analiza-datelor','contabilitate-finante','rezolvarea-problemelor']],
    ['Consilier Bancar','331401',3800,'mediu',['relatii-clienti','comunicare','contabilitate-finante']],
    ['Specialist Recuperare Creanțe','421101',3500,'mediu',['comunicare','legislatie-juridica','vanzare-negociere']],
    ['Specialist Payroll','331303',4000,'mediu',['contabilitate-finante','atentie-detalii','legislatie-juridica']],
    ['Expert Contabil','241401',7000,'mediu',['contabilitate-finante','legislatie-juridica','analiza-datelor']],
    ['Cenzor','241402',5500,'scazut',['contabilitate-finante','legislatie-juridica','atentie-detalii']],
    ['Specialist Conformitate','241205',6000,'mediu',['legislatie-juridica','contabilitate-finante','atentie-detalii']],
    ['Evaluator Bunuri','331501',5000,'mediu',['contabilitate-finante','analiza-datelor','atentie-detalii']],
    ['Specialist Anti-Fraudă','241206',6500,'mediu',['analiza-datelor','legislatie-juridica','rezolvarea-problemelor']],
  ],

  'juridic': [
    ['Avocat','261101',7000,'mediu',['legislatie-juridica','comunicare','rezolvarea-problemelor']],
    ['Notar','261201',8000,'scazut',['legislatie-juridica','atentie-detalii','comunicare']],
    ['Jurist','261301',5000,'mediu',['legislatie-juridica','comunicare','analiza-datelor']],
    ['Executor Judecătoresc','261401',6000,'scazut',['legislatie-juridica','comunicare','planificare-organizare']],
    ['Mediator','261501',4500,'scazut',['comunicare','legislatie-juridica','rezolvarea-problemelor']],
    ['Consilier Juridic','261302',5500,'mediu',['legislatie-juridica','comunicare','rezolvarea-problemelor']],
    ['Paralegal','261303',3500,'mediu',['legislatie-juridica','atentie-detalii','planificare-organizare']],
    ['Grefier','261601',4000,'mediu',['legislatie-juridica','atentie-detalii','planificare-organizare']],
    ['Consultant Management','242101',8000,'mediu',['comunicare','rezolvarea-problemelor','managementul-proiectelor']],
    ['Consultant Resurse Umane','242201',5500,'mediu',['comunicare','legislatie-juridica','planificare-organizare']],
    ['Specialist Proprietate Intelectuală','261304',6000,'scazut',['legislatie-juridica','atentie-detalii','comunicare']],
    ['Consultant Fonduri Europene','242301',5500,'mediu',['managementul-proiectelor','comunicare','legislatie-juridica']],
    ['Lichidator Judiciar','261701',6000,'scazut',['legislatie-juridica','contabilitate-finante','rezolvarea-problemelor']],
    ['Expert Criminalist','261801',5000,'scazut',['analiza-datelor','atentie-detalii','rezolvarea-problemelor']],
    ['Registrator Carte Funciară','335201',4000,'scazut',['legislatie-juridica','atentie-detalii','planificare-organizare']],
    ['Administrator Judiciar','261702',6000,'scazut',['legislatie-juridica','contabilitate-finante','managementul-proiectelor']],
    ['Expert Tehnic Judiciar','261802',5500,'scazut',['rezolvarea-problemelor','analiza-datelor','legislatie-juridica']],
    ['Traducător Autorizat','264101',4500,'mediu',['limbi-straine','comunicare','atentie-detalii']],
    ['Specialist GDPR','261305',5500,'mediu',['legislatie-juridica','securitate-cibernetica','comunicare']],
    ['Consultant Afaceri','242102',6500,'mediu',['comunicare','rezolvarea-problemelor','vanzare-negociere']],
  ],

  'administratie-publica': [
    ['Funcționar Public','411001',4000,'mediu',['planificare-organizare','comunicare','legislatie-juridica']],
    ['Inspector Fiscal','335301',4500,'mediu',['contabilitate-finante','legislatie-juridica','atentie-detalii']],
    ['Polițist','541101',5000,'ridicat',['legislatie-juridica','comunicare','rezolvarea-problemelor','prim-ajutor']],
    ['Pompier','541201',4500,'ridicat',['prim-ajutor','protectia-muncii','lucru-echipa','rezolvarea-problemelor']],
    ['Inspector Muncă','335302',4200,'scazut',['legislatie-juridica','protectia-muncii','comunicare']],
    ['Diplomat','111201',7000,'scazut',['limbi-straine','comunicare','legislatie-juridica']],
    ['Ofițer Stare Civilă','335401',3500,'scazut',['legislatie-juridica','comunicare','atentie-detalii']],
    ['Arhivar','441501',3000,'scazut',['planificare-organizare','atentie-detalii','comunicare']],
    ['Inspector Protecția Mediului','335303',4000,'scazut',['legislatie-juridica','analiza-datelor','comunicare']],
    ['Specialist Achiziții Publice','335304',4500,'mediu',['legislatie-juridica','planificare-organizare','contabilitate-finante']],
    ['Referent Urbanism','335305',4000,'scazut',['legislatie-juridica','citirea-planurilor','comunicare']],
    ['Inspector Sanitar','335306',4200,'mediu',['legislatie-juridica','protectia-muncii','comunicare']],
    ['Agent Poliție Locală','541102',3800,'mediu',['legislatie-juridica','comunicare','rezolvarea-problemelor']],
    ['Inspector Protecția Consumatorului','335307',3800,'scazut',['legislatie-juridica','comunicare','atentie-detalii']],
    ['Meteorolog','211201',4500,'scazut',['analiza-datelor','rezolvarea-problemelor','comunicare']],
    ['Inspector Construcții','335308',4500,'mediu',['citirea-planurilor','legislatie-juridica','atentie-detalii']],
    ['Ofițer Vamal','335102',4500,'mediu',['legislatie-juridica','limbi-straine','comunicare']],
    ['Inspector Școlar','235301',4500,'scazut',['predare-educatie','legislatie-juridica','comunicare']],
    ['Consilier Programe Europene','242302',5000,'mediu',['managementul-proiectelor','comunicare','legislatie-juridica']],
    ['Registrator Medical','441601',3200,'mediu',['atentie-detalii','comunicare','planificare-organizare']],
  ],

  'arte-cultura': [
    ['Actor','265101',4000,'scazut',['comunicare','lucru-echipa','rezolvarea-problemelor']],
    ['Regizor','265201',5500,'scazut',['leadership','comunicare','rezolvarea-problemelor']],
    ['Pictor','265301',3000,'scazut',['design-grafic','atentie-detalii','rezolvarea-problemelor']],
    ['Sculptor','265302',3000,'scazut',['design-grafic','atentie-detalii','rezolvarea-problemelor']],
    ['Muzician','265401',3500,'scazut',['comunicare','lucru-echipa','atentie-detalii']],
    ['Coregraf','265501',3500,'scazut',['comunicare','leadership','fitness-antrenament']],
    ['Fotograf','343101',3500,'mediu',['editare-media','atentie-detalii','comunicare']],
    ['Designer Grafic','216301',5000,'mediu',['design-grafic','programare','comunicare']],
    ['Scenograf','265601',3500,'scazut',['design-grafic','atentie-detalii','lucru-echipa']],
    ['Restaurator Artă','265701',3800,'scazut',['atentie-detalii','rezolvarea-problemelor','design-grafic']],
    ['Curator Muzeu','262101',3500,'scazut',['comunicare','planificare-organizare','atentie-detalii']],
    ['Designer Interior','216302',5000,'mediu',['design-grafic','comunicare','citirea-planurilor']],
    ['Animator 2D/3D','216303',5500,'mediu',['design-grafic','programare','atentie-detalii']],
    ['Designer Produs','216304',5000,'mediu',['design-grafic','rezolvarea-problemelor','comunicare']],
    ['Ilustrator','265801',4000,'scazut',['design-grafic','atentie-detalii','comunicare']],
    ['Bijutier','731101',3500,'scazut',['atentie-detalii','design-grafic','rezolvarea-problemelor']],
    ['Ceramist','731201',3000,'scazut',['atentie-detalii','design-grafic','rezolvarea-problemelor']],
    ['Designer Vestimentar','216305',4500,'mediu',['design-grafic','comunicare','atentie-detalii']],
    ['Grafician','216306',4500,'mediu',['design-grafic','editare-media','atentie-detalii']],
    ['Decorator','343201',3500,'scazut',['design-grafic','atentie-detalii','comunicare']],
  ],

  'media-comunicare': [
    ['Jurnalist','264201',4000,'mediu',['comunicare','rezolvarea-problemelor','limbi-straine']],
    ['Reporter','264202',3500,'mediu',['comunicare','rezolvarea-problemelor','limbi-straine']],
    ['Editor','264301',4000,'mediu',['comunicare','atentie-detalii','planificare-organizare']],
    ['Cameraman','352101',3800,'mediu',['editare-media','atentie-detalii','lucru-echipa']],
    ['Specialist PR','243201',5000,'mediu',['comunicare','marketing-digital','relatii-clienti']],
    ['Copywriter','264302',4500,'mediu',['comunicare','marketing-digital','atentie-detalii']],
    ['Social Media Manager','243202',4500,'ridicat',['marketing-digital','comunicare','design-grafic']],
    ['Specialist SEO','243203',5500,'ridicat',['marketing-digital','analiza-datelor','programare']],
    ['Content Creator','264303',4000,'ridicat',['comunicare','marketing-digital','editare-media']],
    ['Producător TV','265901',5000,'scazut',['comunicare','leadership','planificare-organizare']],
    ['Operator Sunet','352201',3500,'scazut',['atentie-detalii','rezolvarea-problemelor','lucru-echipa']],
    ['Editor Video','352301',4000,'mediu',['editare-media','atentie-detalii','rezolvarea-problemelor']],
    ['Specialist Marketing Digital','243204',5500,'ridicat',['marketing-digital','analiza-datelor','comunicare']],
    ['Brand Manager','243205',6000,'mediu',['marketing-digital','comunicare','leadership']],
    ['Specialist Comunicare','243206',4500,'mediu',['comunicare','marketing-digital','relatii-clienti']],
    ['Prezentator TV','265902',5000,'scazut',['comunicare','limbi-straine','rezolvarea-problemelor']],
    ['Fotoreporter','343102',3500,'scazut',['editare-media','comunicare','atentie-detalii']],
    ['Redactor Șef','264304',5500,'scazut',['comunicare','leadership','planificare-organizare']],
    ['Specialist Media Buying','243207',5000,'mediu',['marketing-digital','analiza-datelor','vanzare-negociere']],
    ['Podcast Producer','265903',4000,'mediu',['editare-media','comunicare','marketing-digital']],
  ],

  'energie-utilitati': [
    ['Inginer Energetician','215101',7000,'mediu',['electricitate','rezolvarea-problemelor','managementul-proiectelor']],
    ['Electrician Întreținere','741102',4500,'ridicat',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Instalator Panouri Solare','741103',4500,'ridicat',['electricitate','citirea-planurilor','protectia-muncii']],
    ['Operator Centrală Electrică','811201',5000,'mediu',['operare-utilaje','electricitate','protectia-muncii']],
    ['Tehnician Eolian','311501',5000,'mediu',['electricitate','operare-utilaje','protectia-muncii']],
    ['Inginer Petrochimist','215201',7500,'mediu',['rezolvarea-problemelor','managementul-proiectelor','protectia-muncii']],
    ['Operator Rețele Gaz','811301',4500,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Sudor Conducte','721102',5000,'mediu',['sudura','protectia-muncii','atentie-detalii']],
    ['Inginer Mediu','214301',5500,'mediu',['analiza-datelor','legislatie-juridica','rezolvarea-problemelor']],
    ['Specialist Eficiență Energetică','215102',5500,'mediu',['analiza-datelor','electricitate','rezolvarea-problemelor']],
    ['Operator Stație Epurare','811401',3800,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Laborant Chimist Industrial','314301',4000,'scazut',['analiza-datelor','atentie-detalii','protectia-muncii']],
    ['Tehnician Rețele Electrice','311502',4500,'mediu',['electricitate','protectia-muncii','rezolvarea-problemelor']],
    ['Operator Rețele Apă','811501',3800,'mediu',['operare-utilaje','protectia-muncii','rezolvarea-problemelor']],
    ['Inginer Gaze Naturale','215301',7000,'mediu',['rezolvarea-problemelor','protectia-muncii','managementul-proiectelor']],
    ['Proiectant Instalații','215401',6000,'mediu',['citirea-planurilor','electricitate','rezolvarea-problemelor']],
    ['Specialist Protecția Mediului','213501',5000,'mediu',['legislatie-juridica','analiza-datelor','comunicare']],
    ['Operator Centrală Termică','811601',3500,'mediu',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Electrician Industrial','741104',4500,'ridicat',['electricitate','protectia-muncii','rezolvarea-problemelor']],
    ['Inginer Energie Regenerabilă','215103',7000,'ridicat',['electricitate','managementul-proiectelor','rezolvarea-problemelor']],
  ],

  'imobiliare': [
    ['Agent Imobiliar','333401',5000,'mediu',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Evaluator Imobiliar','331502',5500,'mediu',['contabilitate-finante','analiza-datelor','atentie-detalii']],
    ['Administrator Imobile','411101',3500,'mediu',['administrare-proprietati','comunicare','planificare-organizare']],
    ['Manager Proprietăți','411102',5000,'mediu',['administrare-proprietati','leadership','planificare-organizare']],
    ['Consultant Imobiliar','333402',4500,'mediu',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Broker Imobiliar','333403',6000,'mediu',['vanzare-negociere','comunicare','legislatie-juridica']],
    ['Inspector Imobiliar','333404',4000,'scazut',['legislatie-juridica','atentie-detalii','comunicare']],
    ['Specialist Cadastru','216502',4500,'mediu',['citirea-planurilor','legislatie-juridica','atentie-detalii']],
    ['Arhitect','216101',7000,'mediu',['design-grafic','citirea-planurilor','rezolvarea-problemelor']],
    ['Inginer Geodez','216503',5000,'scazut',['citirea-planurilor','analiza-datelor','atentie-detalii']],
    ['Dezvoltator Imobiliar','333405',8000,'mediu',['managementul-proiectelor','vanzare-negociere','contabilitate-finante']],
    ['Administrator Asociație Proprietari','411103',3000,'mediu',['administrare-proprietati','comunicare','contabilitate-finante']],
    ['Specialist Închirieri','333406',4000,'mediu',['vanzare-negociere','comunicare','relatii-clienti']],
    ['Analist Piață Imobiliară','333407',5500,'scazut',['analiza-datelor','contabilitate-finante','comunicare']],
    ['Fotograf Imobiliar','343103',3500,'mediu',['editare-media','atentie-detalii','comunicare']],
    ['Specialist Home Staging','343301',3800,'scazut',['design-grafic','atentie-detalii','comunicare']],
    ['Consultant Investiții Imobiliare','333408',7000,'scazut',['contabilitate-finante','analiza-datelor','vanzare-negociere']],
    ['Proiectant Urbanism','216102',5500,'mediu',['citirea-planurilor','legislatie-juridica','comunicare']],
    ['Inginer Instalații Clădiri','215402',6000,'mediu',['citirea-planurilor','electricitate','rezolvarea-problemelor']],
    ['Specialist Property Management','411104',4500,'mediu',['administrare-proprietati','comunicare','planificare-organizare']],
  ],

  'auto-reparatii': [
    ['Mecanic Auto','723102',4000,'ridicat',['mecanica-auto','rezolvarea-problemelor','protectia-muncii']],
    ['Electrician Auto','741301',4200,'ridicat',['mecanica-auto','electricitate','rezolvarea-problemelor']],
    ['Tinichigiu Auto','721301',3800,'mediu',['mecanica-auto','atentie-detalii','protectia-muncii']],
    ['Vopsitor Auto','713201',3800,'mediu',['atentie-detalii','protectia-muncii','mecanica-auto']],
    ['Vulcanizator','812101',3000,'mediu',['mecanica-auto','protectia-muncii','relatii-clienti']],
    ['Specialist Diagnoză Auto','723103',4500,'mediu',['mecanica-auto','rezolvarea-problemelor','analiza-datelor']],
    ['Mecanic Motociclete','723104',3500,'scazut',['mecanica-auto','rezolvarea-problemelor','atentie-detalii']],
    ['Inspector ITP Auto','311402',4500,'mediu',['mecanica-auto','legislatie-juridica','atentie-detalii']],
    ['Electronist Auto','742301',4500,'mediu',['mecanica-auto','electricitate','rezolvarea-problemelor']],
    ['Geamgiu Auto','712401',3000,'scazut',['atentie-detalii','mecanica-auto','protectia-muncii']],
    ['Specialist Climatizare Auto','723105',3800,'mediu',['mecanica-auto','rezolvarea-problemelor','protectia-muncii']],
    ['Mecatronist Auto','742401',5000,'mediu',['mecanica-auto','electricitate','programare']],
    ['Specialist Detailing Auto','812201',3200,'mediu',['atentie-detalii','relatii-clienti','protectia-muncii']],
    ['Specialist Geometrie Roți','723106',3500,'mediu',['mecanica-auto','atentie-detalii','rezolvarea-problemelor']],
    ['Spălător Auto','912001',2500,'mediu',['atentie-detalii','protectia-muncii','relatii-clienti']],
    ['Inginer Automotive','214501',7000,'mediu',['mecanica-auto','rezolvarea-problemelor','managementul-proiectelor']],
    ['Specialist Flote Auto','432401',4000,'mediu',['mecanica-auto','planificare-organizare','gestionare-stocuri']],
    ['Montator Anvelope','812102',2800,'mediu',['mecanica-auto','protectia-muncii','lucru-echipa']],
    ['Specialist Tuning Auto','723107',4000,'scazut',['mecanica-auto','design-grafic','rezolvarea-problemelor']],
    ['Consultant Vânzări Auto','332207',4500,'mediu',['vanzare-negociere','comunicare','mecanica-auto']],
  ],

  'securitate': [
    ['Agent Pază','541301',2800,'ridicat',['protectia-muncii','comunicare','prim-ajutor']],
    ['Bodyguard','541302',4000,'mediu',['protectia-muncii','prim-ajutor','fitness-antrenament']],
    ['Detectiv Particular','541303',4000,'scazut',['rezolvarea-problemelor','comunicare','legislatie-juridica']],
    ['Instalator Sisteme Securitate','741401',4000,'mediu',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Operator CCTV','541304',3000,'mediu',['atentie-detalii','comunicare','protectia-muncii']],
    ['Dispecer Securitate','541305',3200,'mediu',['comunicare','rezolvarea-problemelor','planificare-organizare']],
    ['Consultant Securitate','541306',5000,'mediu',['protectia-muncii','comunicare','rezolvarea-problemelor']],
    ['Inspector Protecție','541307',4000,'mediu',['protectia-muncii','legislatie-juridica','comunicare']],
    ['Agent Securitate Aeroportuară','541308',3500,'mediu',['protectia-muncii','limbi-straine','comunicare']],
    ['Pompier Privat','541309',3500,'mediu',['prim-ajutor','protectia-muncii','lucru-echipa']],
    ['Agent Intervenție Rapidă','541310',3200,'mediu',['protectia-muncii','prim-ajutor','rezolvarea-problemelor']],
    ['Specialist SSM','226901',4500,'mediu',['protectia-muncii','legislatie-juridica','comunicare']],
    ['Inspector SSM','226902',5000,'mediu',['protectia-muncii','legislatie-juridica','managementul-proiectelor']],
    ['Agent Transport Valori','541311',3500,'mediu',['protectia-muncii','conducere-vehicule','atentie-detalii']],
    ['Controlor Acces','541312',2800,'mediu',['comunicare','protectia-muncii','atentie-detalii']],
    ['Specialist Securitate Incendii','226903',4500,'mediu',['protectia-muncii','legislatie-juridica','rezolvarea-problemelor']],
    ['Specialist Securitate Evenimente','541313',3500,'mediu',['protectia-muncii','comunicare','planificare-organizare']],
    ['Operator Monitoring','541314',3000,'mediu',['atentie-detalii','comunicare','rezolvarea-problemelor']],
    ['Instructor Autoapărare','342201',3500,'scazut',['fitness-antrenament','comunicare','predare-educatie']],
    ['Manager Securitate','143901',6000,'mediu',['leadership','protectia-muncii','managementul-proiectelor']],
  ],

  'curatenie-mentenanta': [
    ['Agent Curățenie','911101',2500,'ridicat',['protectia-muncii','atentie-detalii','lucru-echipa']],
    ['Administrator Clădire','515101',3500,'mediu',['administrare-proprietati','planificare-organizare','comunicare']],
    ['Instalator Mentenanță','712603',3800,'mediu',['rezolvarea-problemelor','citirea-planurilor','protectia-muncii']],
    ['Electrician Mentenanță','741105',4000,'mediu',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Grădinar Mentenanță','921101',2800,'mediu',['agricultura-zootehnie','atentie-detalii','protectia-muncii']],
    ['Specialist DDD','754101',3200,'mediu',['protectia-muncii','rezolvarea-problemelor','atentie-detalii']],
    ['Operator Spălătorie','815101',2500,'scazut',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Tehnician HVAC','712701',4500,'mediu',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Mecanic Ascensoare','723401',4200,'mediu',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Specialist Curățenie Industrială','911102',3000,'mediu',['protectia-muncii','operare-utilaje','lucru-echipa']],
    ['Gestionar Deșeuri','961101',2800,'mediu',['protectia-muncii','planificare-organizare','legislatie-juridica']],
    ['Operator Reciclare','961201',2800,'scazut',['operare-utilaje','protectia-muncii','atentie-detalii']],
    ['Zugrav Mentenanță','713102',3200,'mediu',['atentie-detalii','protectia-muncii','lucru-echipa']],
    ['Lăcătuș Mentenanță','722202',3800,'mediu',['rezolvarea-problemelor','operare-utilaje','protectia-muncii']],
    ['Portar','962101',2500,'scazut',['comunicare','atentie-detalii','protectia-muncii']],
    ['Îngrijitor Spații Verzi','921201',2800,'mediu',['agricultura-zootehnie','protectia-muncii','atentie-detalii']],
    ['Facility Manager','515201',5000,'mediu',['administrare-proprietati','leadership','planificare-organizare']],
    ['Tehnician Frigotehnist','712801',4200,'mediu',['electricitate','rezolvarea-problemelor','protectia-muncii']],
    ['Specialist Pest Control','754201',3200,'mediu',['protectia-muncii','rezolvarea-problemelor','comunicare']],
    ['Muncitor Întreținere','961301',2800,'mediu',['rezolvarea-problemelor','protectia-muncii','lucru-echipa']],
  ],

  'sport-fitness': [
    ['Antrenor Personal','342301',4000,'ridicat',['fitness-antrenament','comunicare','relatii-clienti']],
    ['Instructor Fitness','342302',3500,'ridicat',['fitness-antrenament','comunicare','prim-ajutor']],
    ['Antrenor Fotbal','342303',4000,'mediu',['fitness-antrenament','leadership','comunicare']],
    ['Instructor Yoga','342304',3500,'mediu',['fitness-antrenament','comunicare','relatii-clienti']],
    ['Nutriționist Sportiv','226502',4500,'mediu',['fitness-antrenament','analiza-datelor','comunicare']],
    ['Fizioterapeut Sportiv','226305',5000,'mediu',['ingrijirea-pacientilor','fitness-antrenament','rezolvarea-problemelor']],
    ['Instructor Natație','342305',3200,'mediu',['fitness-antrenament','prim-ajutor','comunicare']],
    ['Antrenor Box','342306',3500,'scazut',['fitness-antrenament','comunicare','prim-ajutor']],
    ['Instructor Dans','342307',3000,'scazut',['fitness-antrenament','comunicare','lucru-echipa']],
    ['Kinetoterapeut Sportiv','226306',4500,'mediu',['ingrijirea-pacientilor','fitness-antrenament','rezolvarea-problemelor']],
    ['Manager Sală Fitness','143902',5000,'mediu',['leadership','planificare-organizare','relatii-clienti']],
    ['Arbitru','342308',3500,'scazut',['atentie-detalii','comunicare','fitness-antrenament']],
    ['Instructor Ciclism','342309',3200,'scazut',['fitness-antrenament','prim-ajutor','comunicare']],
    ['Antrenor Atletism','342310',3500,'scazut',['fitness-antrenament','leadership','comunicare']],
    ['Instructor Arte Marțiale','342311',3200,'mediu',['fitness-antrenament','comunicare','prim-ajutor']],
    ['Preparator Fizic','342312',4500,'mediu',['fitness-antrenament','analiza-datelor','rezolvarea-problemelor']],
    ['Maseur Sportiv','325502',3500,'mediu',['ingrijirea-pacientilor','fitness-antrenament','comunicare']],
    ['Instructor Pilates','342313',3200,'mediu',['fitness-antrenament','comunicare','relatii-clienti']],
    ['Specialist Recuperare Sportivă','226307',4500,'mediu',['ingrijirea-pacientilor','fitness-antrenament','rezolvarea-problemelor']],
    ['Monitor Schi','342314',3000,'scazut',['fitness-antrenament','prim-ajutor','comunicare']],
  ],
};
